wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1666006444.662623
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 2
      - 16
      - 23
      4: 3.9.12
      5: 0.13.4
      8:
      - 1
      - 5
architecture:
  desc: null
  value: Neural Style Transfer
content_alpha:
  desc: null
  value: 1
epochs:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.01
style_beta:
  desc: null
  value: 5
